# Generated by Django 5.1.6 on 2025-02-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.TextField()),
                ('desc', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('pic', models.ImageField(null=True, upload_to='products/')),
            ],
        ),
    ]
